In [1]:
import numpy as np
import torch

from detectron2.utils.logger import setup_logger
setup_logger()

from detectron2.config import get_cfg
from detectron2 import model_zoo

In [2]:
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file('COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'))
cfg.MODEL.ROI_HEADS.SCORE_THRES_TEST = 0.5
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url('COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml')

In [5]:
meta_arch = cfg.MODEL.META_ARCHITECTURE
print(f'META_ARCHITECTURE: {meta_arch}')

META_ARCHITECTURE: GeneralizedRCNN


In [8]:
print(f'input_format : {cfg.INPUT.FORMAT}')
print(f'vis_period   : {cfg.VIS_PERIOD}')
print(f'pixel_mean   : {cfg.MODEL.PIXEL_MEAN}')
print(f'pixel_std    : {cfg.MODEL.PIXEL_STD}')

input_format : BGR
vis_period   : 0
pixel_mean   : [103.53, 116.28, 123.675]
pixel_std    : [1.0, 1.0, 1.0]


In [9]:
print(f'backbone_name : {cfg.MODEL.BACKBONE.NAME}')

backbone_name : build_resnet_fpn_backbone


In [10]:
from collections import namedtuple

class ShapeSpec(namedtuple("_ShapeSpec", ["channels", "height", "width", "stride"])):
    """
    A simple structure that containes basic shpae specification about a tensor.
    It is often used as the auxiliary inputs/outputs of models,
    to complement the lack of shape inference ability among pytorch modules.

    Attributes:
        channels:
        height:
        width:
        stride:
    """

    def __new__(cls, channels=None, height=None, width=None, stride=None):
        return super().__new__(cls, channels, height, width, stride)

In [11]:
input_shape = ShapeSpec(channels=len(cfg.MODEL.PIXEL_MEAN))
input_shape

ShapeSpec(channels=3, height=None, width=None, stride=None)

In [12]:
in_features = cfg.MODEL.FPN.IN_FEATURES
out_channels = cfg.MODEL.FPN.OUT_CHANNELS

In [13]:
print(f'norm: {cfg.MODEL.RESNETS.NORM}')
print(f'stem_out_channels: {cfg.MODEL.RESNETS.STEM_OUT_CHANNELS}')

norm: FrozenBN
stem_out_channels: 64


In [14]:
print(f'freeze_at: {cfg.MODEL.BACKBONE.FREEZE_AT}')
print(f'out_features: {cfg.MODEL.RESNETS.OUT_FEATURES}')
print(f'depth: {cfg.MODEL.RESNETS.DEPTH}')
print(f'num_groups: {cfg.MODEL.RESNETS.NUM_GROUPS}')
print(f'width_per_group: {cfg.MODEL.RESNETS.WIDTH_PER_GROUP}')
print(f'in_channels: {cfg.MODEL.RESNETS.STEM_OUT_CHANNELS}')
print(f'out_channels: {cfg.MODEL.RESNETS.RES2_OUT_CHANNELS}')
print(f'stride_in_1x1: {cfg.MODEL.RESNETS.STRIDE_IN_1X1}')
print(f'res5_dilation: {cfg.MODEL.RESNETS.RES5_DILATION}')
print(f'deform_on_per_stage: {cfg.MODEL.RESNETS.DEFORM_ON_PER_STAGE}')
print(f'deform_modulated: {cfg.MODEL.RESNETS.DEFORM_MODULATED}')
print(f'deform_num_groups: {cfg.MODEL.RESNETS.DEFORM_NUM_GROUPS}')

freeze_at: 2
out_features: ['res2', 'res3', 'res4', 'res5']
depth: 50
num_groups: 1
width_per_group: 64
in_channels: 64
out_channels: 256
stride_in_1x1: True
res5_dilation: 1
deform_on_per_stage: [False, False, False, False]
deform_modulated: False
deform_num_groups: 1


In [ ]:
def build_resnet_backbone(cfg, input_shape):
    """
    Create a ResNet instance from config.

    Returns:
        ResNet: a :class:`ResNet` instance.
    """
    norm


In [18]:
import yaml

with open('config.yaml', 'w') as f:
    f.write(cfg.dump())

In [2]:
import torch

In [8]:
conv2d = torch.nn.Conv2d(
    in_channels=3,
    out_channels=3,
    kernel_size=1,
    stride=2,
    bias=False,
)

In [9]:
input2d = torch.ones([1, 3, 4, 4])
output2d = conv2d(input2d)
output2d.shape

torch.Size([1, 3, 2, 2])

In [10]:
out = torch.chunk(output2d, 3, dim=1)

In [11]:
out

(tensor([[[[-0.9640, -0.9640],
           [-0.9640, -0.9640]]]], grad_fn=<SplitBackward0>),
 tensor([[[[0.9791, 0.9791],
           [0.9791, 0.9791]]]], grad_fn=<SplitBackward0>),
 tensor([[[[0.8470, 0.8470],
           [0.8470, 0.8470]]]], grad_fn=<SplitBackward0>))

In [13]:
import numpy as np

d = 2
base = 3

offset = np.full((base**d, d), -1)

for i in range(base ** d):
    tmp_i = i
    for j in range(d):
        print(f"offset[{i}][{j}] = {tmp_i % base - 1}")
        tmp_i = tmp_i // base


offset[0][0] = -1
offset[0][1] = -1
offset[1][0] = 0
offset[1][1] = -1
offset[2][0] = 1
offset[2][1] = -1
offset[3][0] = -1
offset[3][1] = 0
offset[4][0] = 0
offset[4][1] = 0
offset[5][0] = 1
offset[5][1] = 0
offset[6][0] = -1
offset[6][1] = 1
offset[7][0] = 0
offset[7][1] = 1
offset[8][0] = 1
offset[8][1] = 1
